apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-propagator-fm3n
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:48618d82c1c81af76c0ec6d781e58877e91af5d0e0caf37ba327abdc62220495
        name: container-image
        resources: {}
status: {}
