apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-propagator-fm3n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-propagator-fm3n
    app.kubernetes.io/part-of: governance-policy-propagator
  name: governance-policy-propagagrw8
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: governance-policy-propagator-fm3n
    weight: 100
status: {}
