apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-propagator-fm3n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-propagator-fm3n
    app.kubernetes.io/part-of: governance-policy-propagator
  name: governance-policy-propagator-fm3n
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-propagator-fm3n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-propagator-fm3n
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-propagator/governance-policy-propagator-fm3n@sha256:b7d5e5f39a2efb0636422d758a58114e342d431e7241bd1f8ff7acc2ba3decc7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
